### ISSUE TITLE
SIU to JSON channel template doesn't return RGS portion

### ISSUE THREAD

**Issue by asharafshahi** [daticahealth/Mirth-Transforms#5]
I tried importing the SIU HL7 to JSON conversion into a Mirth 3.5.1 and sent the following message in, but the RGS property of the resulting JSON object is always [{}].  Any idea what might be causing that?

`MSH|^~\&|ATHENANET|99999^MA - athenahealth Testing^1^Test Clinic|TestInterface||201505181411||SIU^S12|185M90009|T|2.3.1
SCH|30148|30148||||Total Knee Replacement|Followup Surgery|RWFU^RWMA-FOLLOWUP|60|minutes|^^^201801271200|||||username|||||||||BOOKED
PID||105613|105613|105613|LASTNAME^FIRSTNAME^MIDDLENNAME^SUFFIX||19880601|M|PREFERREDNAME|2028-9^Asian|ADDRESS^ADDRESS (CTD)^CITY^STATE^00000^COUNTRY||(111)111-1111^PRN^PH^^1^111^1111111~(333)333-3333^WPN^PH^^1^333^3333333~Patientemail@email.com^NET^^Patientemail@email.com~(222)222-2222^ORN^CP^^1^222^2222222|(333)333-3333^WPN^PH^^1^333^3333333|eng^English|S|||000000000||ATHENA|2186-5^Not Hispanic or Latino
PD1||||A12123^PCPLASTNAME^PCPFIRSTNAME
PV1|||9^TEST DEPARTMENT^^TEST DEPARTMENT||||12345678^SEUSS^DOCTOR||||||||||12345678^SEUSS^DOCTOR||33910|||||||||||||||||||||||||||||||33910
AIG|||providerusername|||||201505191300|||15|minutes
AIL|||9^TEST DEPARTMENT|||201505191300|||90|minutes
AIP|1|A|90410^^^^^^^^^^^^MD| Wait Time`

**Comment by rwattras9** [comment]
Hi there, it looks like the reason is that there is no RGS (Resource Group) segment in that SIU message prior to the AI* segments. Per the HL7 spec, RGS is a required segment and is what groups the appointment resource segments (AIP, AIS, etc) together.
If you wanted to be able to pull those fields into the JSON, you'd need to add an RGS segment after the PV1; and it can even be blank, like this:

MSH|^~\&|ATHENANET|99999^MA - athenahealth Testing^1^Test Clinic|TestInterface||201505181411||SIU^S12|185M90009|T|2.3.1 
SCH|30148|30148||||Total Knee Replacement|Followup Surgery|RWFU^RWMA-FOLLOWUP|60|minutes|^^^201801271200|||||username|||||||||BOOKED 
PID||105613|105613|105613|LASTNAME^FIRSTNAME^MIDDLENNAME^SUFFIX||19880601|M|PREFERREDNAME|2028-9^Asian|ADDRESS^ADDRESS (CTD)^CITY^STATE^00000^COUNTRY||(111)111-1111^PRN^PH^^1^111^1111111~(333)333-3333^WPN^PH^^1^333^3333333~Patientemail@email.com^NET^^Patientemail@email.com~(222)222-2222^ORN^CP^^1^222^2222222|(333)333-3333^WPN^PH^^1^333^3333333|eng^English|S|||000000000||ATHENA|2186-5^Not Hispanic or Latino 
PD1||||A12123^PCPLASTNAME^PCPFIRSTNAME 
PV1|||9^TEST DEPARTMENT^^TEST DEPARTMENT||||12345678^SEUSS^DOCTOR||||||||||12345678^SEUSS^DOCTOR||33910|||||||||||||||||||||||||||||||33910 
RGS|
AIG|||providerusername|||||201505191300|||15|minutes 
AIL|||9^TEST DEPARTMENT|||201505191300|||90|minutes 
AIP|1|A|90410^^^^^^^^^^^^MD| Wait Time

You should now see the RGS block being populated.

If that message is being generated by an external system that doesn't send the RGS segment, then you'll have to adjust the AI* segment transforms to skip the RGS processing and just pull the AI* data right from the segments directly. Let us know if you need any additional guidance on that! 

Hope that helps, and thank you for using our transforms! Let us know if you run into any more issues!

-Datica

**Comment by asharafshahi** [comment]
Thanks @rwattras9, that indeed was the issue and after adding in the required segment everything worked fine.  Oddly, this sample came from Athena's official SIU example message :-)  

Thanks for the tip on how to tweak the transforms, I'll keep that in mind if it becomes necessary.  And thanks for providing these resources to the community, very helpful!
